// Generated by claude.ai

const OgImage = () => {
  const plainText = 'sum_{n=1}^{\\infty} 1/n^2'
  const latexText = '\\sum_{n=1}^{\\infty} \\frac{1}{n^2}'

  const symbols = [
    { s: '∑', x: '6%', y: '10%', sz: '72px', r: '-18deg', o: 0.1 },
    { s: '∫', x: '87%', y: '7%', sz: '64px', r: '12deg', o: 0.09 },
    { s: '∂', x: '3%', y: '60%', sz: '52px', r: '-6deg', o: 0.08 },
    { s: '√', x: '90%', y: '58%', sz: '56px', r: '20deg', o: 0.09 },
    { s: 'π', x: '77%', y: '80%', sz: '44px', r: '-14deg', o: 0.1 },
    { s: 'λ', x: '13%', y: '82%', sz: '44px', r: '8deg', o: 0.08 },
    { s: '∇', x: '91%', y: '33%', sz: '38px', r: '-4deg', o: 0.07 },
    { s: '∞', x: '2%', y: '36%', sz: '36px', r: '6deg', o: 0.07 },
    { s: '≡', x: '70%', y: '12%', sz: '32px', r: '0deg', o: 0.09 },
    { s: 'α', x: '50%', y: '88%', sz: '32px', r: '-10deg', o: 0.08 },
    { s: 'Δ', x: '23%', y: '5%', sz: '28px', r: '15deg', o: 0.07 },
    { s: '⊗', x: '44%', y: '4%', sz: '24px', r: '5deg', o: 0.06 },
  ]

  return (
    <div className="grid min-h-dvh place-items-center bg-[#060912]">
      <style>{`
        @keyframes beam {
          0%   { transform: translateX(-100%) skewX(-12deg); opacity: 0; }
          10%  { opacity: 1; }
          90%  { opacity: 1; }
          100% { transform: translateX(700%) skewX(-12deg); opacity: 0; }
        }
        @keyframes grid-pulse {
          0%, 100% { opacity: 0.4; }
          50%       { opacity: 0.7; }
        }
        @keyframes badge-in {
          from { opacity: 0; transform: translateY(6px); }
          to   { opacity: 1; transform: translateY(0); }
        }
        .scan-beam  { animation: beam 5s ease-in-out infinite; animation-delay: 1s; }
        .grid-bg    { animation: grid-pulse 6s ease-in-out infinite; }
        .badge-pop  { animation: badge-in 0.6s ease forwards; }
      `}</style>

      <div
        id="og-image"
        className="relative flex h-[630px] w-[1200px] flex-col items-center justify-center overflow-hidden"
        style={{ background: 'linear-gradient(145deg, #07101f 0%, #060912 55%, #080614 100%)' }}
      >
        {/* Grid texture */}
        <div
          className="grid-bg pointer-events-none absolute inset-0"
          style={{
            backgroundImage: `
              linear-gradient(rgba(14,105,255,0.07) 1px, transparent 1px),
              linear-gradient(90deg, rgba(14,105,255,0.07) 1px, transparent 1px)
            `,
            backgroundSize: '60px 60px',
          }}
        />

        {/* Centre radial glow */}
        <div
          className="pointer-events-none absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2"
          style={{
            width: '860px',
            height: '480px',
            background: 'radial-gradient(ellipse, rgba(14,105,255,0.13) 0%, transparent 68%)',
          }}
        />

        {/* Top-left corner glow */}
        <div
          className="pointer-events-none absolute -top-20 -left-20"
          style={{
            width: '320px',
            height: '320px',
            background: 'radial-gradient(circle, rgba(14,105,255,0.1) 0%, transparent 70%)',
          }}
        />

        {/* Scan beam */}
        <div
          className="scan-beam pointer-events-none absolute top-0 left-0 h-full w-32 opacity-0"
          style={{
            background: 'linear-gradient(90deg, transparent, rgba(14,105,255,0.06), transparent)',
          }}
        />

        {/* Top / bottom rules */}
        <div
          className="absolute top-8 right-10 left-10 h-px"
          style={{
            background:
              'linear-gradient(90deg, transparent, rgba(14,105,255,0.4) 30%, rgba(14,105,255,0.4) 70%, transparent)',
          }}
        />
        <div
          className="absolute right-10 bottom-8 left-10 h-px"
          style={{
            background:
              'linear-gradient(90deg, transparent, rgba(14,105,255,0.4) 30%, rgba(14,105,255,0.4) 70%, transparent)',
          }}
        />

        {/* Corner brackets */}
        <div className="absolute top-8 left-8">
          <div
            className="h-5 w-5 border-t-2 border-l-2"
            style={{ borderColor: 'rgba(14,105,255,0.5)' }}
          />
        </div>
        <div className="absolute top-8 right-8">
          <div
            className="h-5 w-5 border-t-2 border-r-2"
            style={{ borderColor: 'rgba(14,105,255,0.5)' }}
          />
        </div>
        <div className="absolute bottom-8 left-8">
          <div
            className="h-5 w-5 border-b-2 border-l-2"
            style={{ borderColor: 'rgba(14,105,255,0.5)' }}
          />
        </div>
        <div className="absolute right-8 bottom-8">
          <div
            className="h-5 w-5 border-r-2 border-b-2"
            style={{ borderColor: 'rgba(14,105,255,0.5)' }}
          />
        </div>

        {/* Floating math symbols */}
        {symbols.map((s, i) => (
          <div
            key={i}
            className="pointer-events-none absolute font-sans select-none"
            style={{
              left: s.x,
              top: s.y,
              fontSize: s.sz,
              opacity: s.o,
              transform: `rotate(${s.r})`,
              color: '#0e69ff',
            }}
          >
            {s.s}
          </div>
        ))}

        {/* ── CONTENT ── */}
        <div className="relative flex flex-col items-center gap-5 px-12 text-center">
          {/* Eyebrow badge */}
          <div
            className="badge-pop flex items-center gap-2 rounded-full px-4 py-1.5 font-mono text-xs font-medium tracking-widest uppercase"
            style={{
              background: 'rgba(14,105,255,0.1)',
              border: '1px solid rgba(14,105,255,0.3)',
              color: '#0e69ff',
            }}
          >
            <span
              className="inline-block h-1.5 w-1.5 rounded-full"
              style={{ background: '#0e69ff', boxShadow: '0 0 6px #0e69ff' }}
            />
            Math Typesetting Tool
          </div>

          {/* Logo + Title */}
          <div className="flex items-center gap-6">
            <img
              src="/favicon.svg"
              className="size-24"
              alt="Plain2TeX"
              style={{ filter: 'drop-shadow(0 0 28px rgba(14,105,255,0.6))' }}
            />
            <h1
              className="font-sans text-white"
              style={{
                fontSize: '7rem',
                fontWeight: 800,
                lineHeight: 1,
                letterSpacing: '-0.03em',
                textShadow: '0 0 60px rgba(14,105,255,0.25)',
              }}
            >
              Plain<span style={{ color: '#0e69ff' }}>2</span>TeX
            </h1>
          </div>

          {/* Conversion strip — backslashes now survive via hoisted consts */}
          <div
            className="flex items-center gap-4 rounded-lg px-7 py-3"
            style={{
              background: 'rgba(14,105,255,0.06)',
              border: '1px solid rgba(14,105,255,0.18)',
            }}
          >
            <span className="font-mono text-base" style={{ color: 'rgba(255,255,255,0.4)' }}>
              {plainText}
            </span>
            <span style={{ color: 'rgba(14,105,255,0.7)', fontSize: '1.3rem' }}>→</span>
            <span className="font-mono text-base" style={{ color: '#0e69ff' }}>
              {latexText}
            </span>
          </div>

          {/* Description */}
          <p
            className="max-w-xl font-sans text-lg  leading-relaxed"
            style={{
              color: 'rgba(255,255,255,0.35)',
              fontWeight: 400,
            }}
          >
            Convert plain-text math expressions to professionally typeset LaTeX instantly. Export as{' '}
            <span style={{ color: 'rgba(255,255,255,0.55)' }}>PNG</span> or{' '}
            <span style={{ color: 'rgba(255,255,255,0.55)' }}>SVG</span> with one click.
          </p>

          {/* Feature pills */}
          <div className="flex items-center gap-2">
            {['Instant Conversion', 'PNG Export', 'SVG Export', 'No Sign-up'].map((tag, i) => (
              <span
                key={i}
                className="rounded px-3 py-1 font-mono text-xs tracking-widest uppercase"
                style={{
                  background: 'rgba(255,255,255,0.03)',
                  border: '1px solid rgba(255,255,255,0.08)',
                  color: 'rgba(255,255,255,0.3)',
                }}
              >
                {tag}
              </span>
            ))}
          </div>
        </div>
      </div>
    </div>
  )
}

export default OgImage
